# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: biorbd_eigen
channels:
- conda-forge
- default
dependencies:
- python >=3.10
- eigen
- rbdl >=3.3.0
- scipy
- ezc3d
- tinyxml
- ipopt
